version: '2'

networks:
  wodbook_network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.30.0.0/24
        gateway: 172.30.0.1

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
     - "27017:27017"
    networks:
      - wodbook_network
